apiVersion: v1
kind: Service
metadata:
  name: {{ include "dgca-verifier-service.fullname" . }}
  labels:
    {{- include "dgca-verifier-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
# Start Context Hack
    - port: 8081
      targetPort: http-context
      protocol: TCP
      name: http-context
# End Context Hack
  selector:
    {{- include "dgca-verifier-service.selectorLabels" . | nindent 4 }}
