{{- if .Values.aadPodIdentity.enabled }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: {{ include "dgc-gateway.fullname" . }}
spec:
  type: 0
  resourceID: "{{ .Values.aadPodIdentity.resourceID }}"
  clientID: "{{ .Values.aadPodIdentity.clientID }}"

---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: {{ include "dgc-gateway.fullname" . }}-binding
spec:
  azureIdentity: {{ include "dgc-gateway.fullname" . }}
  selector: {{ include "dgc-gateway.fullname" . }}-identity
{{- end }}
