apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dgc-gateway.fullname" . }}
  labels:
    {{- include "dgc-gateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dgc-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/kv-secret-provider: {{ include (print $.Template.BasePath "/kv-secret-provider.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- if .Values.aadPodIdentity.enabled }}
        aadpodidbinding: {{ include "dgc-gateway.fullname" . }}-identity
        {{- end }}
        {{- include "dgc-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dgc-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /management/health/readiness
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: JAVA_OPTS
              value: "-Dspring.config.additional-location=file:/dgc/ -Xms256M -Xmx1G"
            - name: "SPRING_PROFILES_ACTIVE"
              value: "mysql,docker,azure,k8s"
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
            - name: config
              mountPath: "/dgc/application-k8s.yml"
              subPath: application-k8s.yml
              readOnly: true
            - name: config
              mountPath: "/dgc/application-azure.yml"
              subPath: application-azure.yml
              readOnly: true
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ include "dgc-gateway.fullname" . }}-secret-provider
      - name: config
        configMap:
          name: {{ include "dgc-gateway.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
