apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dgc-gateway.fullname" . }}-trusted-party-config
  labels:
    {{- include "dgc-gateway.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
data:
{{ (.Files.Glob "trusted-party/*").AsConfig | indent 2 }}
{{- range $index, $values := .Values.trustedParties }}
  trusted-party-{{ $values.country }}-{{ $values.certificate_type }}.json: |
    {{- mustToJson $values | nindent 4 }}
{{- end }}
