apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "dgc-gateway.fullname" . }}-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "{{ .Values.secretProviderClass.keyvaultName }}"
    tenantId: "{{ .Values.secretProviderClass.tenantId }}"
    objects: |
      array:
        - |
          objectName: {{ .Values.secretProviderClass.trustanchorCertificateName }}
          objectVersion: {{ .Values.secretProviderClass.trustanchorCertificateVersion }}
          objectType: secret
          objectAlias: ta.p12
          objectFormat: pfx
          objectEncoding: base64
