apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dgc-gateway.fullname" . }}
  labels:
    {{- include "dgc-gateway.labels" . | nindent 4 }}
data:
  ca.crt: "{{ .Values.dgc.trustanchor_cert_content }}"
