apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dgca-issuance-web.fullname" . }}
  labels:
    {{- include "dgca-issuance-web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dgca-issuance-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- if .Values.aadPodIdentity.enabled }}
        aadpodidbinding: {{ include "dgca-issuance-web.fullname" . }}-aad-identity
        {{- end }}
        {{- include "dgca-issuance-web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dgca-issuance-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/templates/
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: "DGCA_ISSUANCE_SERVICE_URL"
              value: "{{ .Values.dgc.issuance_service_url }}"
            - name: "DGCA_BUSINESSRULE_SERVICE_URL"
              value: "{{ .Values.dgc.businessrule_service_url }}"
      volumes:
      - name: nginx-config-volume
        configMap:
          name: {{ include "dgca-issuance-web.fullname" . }}-nginx-config
          items:
          - key: default.conf.template
            path: default.conf.template
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
