{{- if .Values.aadPodIdentity.enabled }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: {{ include "mysql-aad-setup.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "0"
spec:
  type: 0
  resourceID: "{{ .Values.aadPodIdentity.resourceID }}"
  clientID: "{{ .Values.aadPodIdentity.clientID }}"

---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: {{ include "mysql-aad-setup.fullname" . }}-binding
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "0"
spec:
  azureIdentity: {{ include "mysql-aad-setup.fullname" . }}
  selector: {{ include "mysql-aad-setup.fullname" . }}-identity
{{- end }}
