apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql-aad-setup.fullname" . }}-config
  labels:
    {{- include "mysql-aad-setup.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "0"
data:
{{ (.Files.Glob "db-init/*").AsConfig | indent 2 }}
