---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "msal-authentication.fullname" . }}-secret-provider
spec:
  provider: azure
  secretObjects:
  - secretName: {{ include "msal-authentication.fullname" . }}-secret
    type: Opaque
    data:
    - key: AzureAd__ClientSecret
      objectName: {{ .Values.secretProviderClass.ClientSecret }}
  parameters:
    usePodIdentity: "true"
    keyvaultName: "{{ .Values.secretProviderClass.keyvaultName }}"
    tenantId: "{{ .Values.secretProviderClass.tenantId }}"
    objects: |
      array:
        - |
          objectName: {{ .Values.secretProviderClass.ClientSecret }}
          objectType: secret