apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "msal-authentication.fullname" . }}-pvc
  labels:
    {{- include "msal-authentication.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi