apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "dgca-issuance-service.fullname" . }}-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "{{ .Values.secretProviderClass.keyvaultName }}"
    tenantId: "{{ .Values.secretProviderClass.tenantId }}"
    objects: |
      array:
        - |
          objectName: {{ .Values.secretProviderClass.trustanchorSecretName }}
          objectVersion: {{ .Values.secretProviderClass.trustanchorSecretVersion }}
          objectType: secret
          objectAlias: trustanchor.p12
          objectEncoding: base64
        - |
          objectName: {{ .Values.secretProviderClass.tlsTrustStoreSecretName }}
          objectVersion: {{ .Values.secretProviderClass.tlsTrustStoreSecretVersion }}
          objectType: secret
          objectAlias: tls_trust_store.p12
          objectEncoding: base64
        - |
          objectName: {{ .Values.secretProviderClass.tlsKeyStoreCertificateName }}
          objectVersion: {{ .Values.secretProviderClass.tlsKeyStoreCertificateVersion }}
          objectType: secret
          objectAlias: tls_key_store.p12
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: {{ .Values.secretProviderClass.uploadKeyStoreCertificateName }}
          objectVersion: {{ .Values.secretProviderClass.uploadKeyStoreCertificateVersion }}
          objectType: secret
          objectAlias: upload.p12
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: {{ .Values.secretProviderClass.dscKeyStoreCertificateName }}
          objectVersion: {{ .Values.secretProviderClass.dscKeyStoreCertificateVersion }}
          objectType: secret
          objectAlias: dsc.p12
          objectFormat: pfx
          objectEncoding: base64
