name: CI

on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

jobs:
  lint-terraform:
    runs-on: ubuntu-latest

    container:
      image: "ghcr.io/azure/eu-digital-covid-certificates-reference-architecture/devcontainer:latest"
      options: --user 1001
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint Terraform
        run: |
          terraform fmt -check -recursive

  build-docs:
    runs-on: ubuntu-latest

    container:
      image: "ghcr.io/azure/eu-digital-covid-certificates-reference-architecture/devcontainer:latest"
      options: --user 1001
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docs
        run: |
          cd docs && make

      - name: Upload docs artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: |
            docs/public/

  publish-docs:
    runs-on: ubuntu-latest

    needs: build-docs

    if: ${{ github.event_name == 'push' }} 

    steps:
      - name: Download docs artifacts
        uses: actions/download-artifact@v2
        with:
          name: docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
