name: Build and Publish DevContainer image

on:
  push:
    branches:
      - 'main'
    paths:
      - '.devcontainer/**'

env:
  REGISTRY: ghcr.io

jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .devcontainer/
          push: true
          tags: ${{ env.REGISTRY }}/azure/eu-digital-covid-certificates-reference-architecture/devcontainer:latest
