# Sourced from https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/blob/d312c29132477faeb2a2b69d4adb4b1bab533a81/.github/workflows/ci.yml

# Copyright (C) 2021 T-Systems International GmbH and all other contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Upstream: dgca-wallet-app-android"

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'upstream/dgca-wallet-app-android'
      - 'upstream/patches/dgca-wallet-app-android/**'
      - '.github/workflows/upstream-dgca-wallet-app-android.yml'
  push:
    branches:
      - main
    paths:
      - 'upstream/dgca-wallet-app-android'
      - 'upstream/patches/dgca-wallet-app-android/**'
      - '.github/workflows/upstream-dgca-wallet-app-android.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: patch-app
        working-directory: ./upstream/dgca-wallet-app-android
        run: >-
          for f in ../patches/dgca-wallet-app-android/*.patch; do
          patch -p1 < $f;
          done;
      - name: patch-core
        working-directory: ./upstream/dgca-app-core-android
        run: >-
          for f in ../patches/dgca-app-core-android/*.patch; do
          patch -p1 < $f;
          done;
      - uses: android-actions/setup-android@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: build
        working-directory: ./upstream/dgca-wallet-app-android
        run: |-
          ./gradlew --no-daemon build -PCONFIG_FILE_NAME="verifier-context.jsonc"

      - name: Archive apks
        uses: actions/upload-artifact@v2
        with:
          name: apks
          path: |
            ./upstream/dgca-wallet-app-android/app/build/outputs/apk/acc/release/*
            ./upstream/dgca-wallet-app-android/app/build/outputs/apk/acc/debug/*
          retention-days: 5
